# Simplified PyPI release pipeline

parameters:
- name: releaseType
  displayName: Release Type
  type: string
  default: Test
  values:
  - Test
  - Production

variables:
  poolImage: "ubuntu-latest"
  poolPythonVersion: 3.6

trigger: none # No CI build

pr: none # Not for pull requests

# ==============================================

stages:
- stage: PredeploymentValidation
  displayName: Predeployment Validation
  pool:
    vmImage: $(PoolImage)
    
  jobs:
  - job: Placeholder
    pool: server

    steps:
    - task: Delay@1
      displayName: "Placeholder Pause"
      inputs:
        delayForMinutes: "0"

# ==============================================

- template: templates/create-wheel-stage-template.yml
  parameters:
    stageName: CreateWheel
    previousStages: PredeploymentValidation
    poolImage: $(PoolImage)
    poolPythonVersion: 3.7
    packageArtifactName: Wheels
    versionArtifactName: Version
    versionFileName: versionInfo.txt
    freezeArtifactStem: CreateWheelFreeze
    freezeFile: requirements-freeze.txt

# ==============================================

- template: templates/wheel-artifact-tests-stage-template.yml
  parameters:
    stageName: TestWheel
    previousStages: CreateWheel
    poolImage: $(PoolImage)
    poolPythonVersion: 3.7
    packageArtifactName: Wheels
    freezeArtifactStem: TestWheelFreeze

# ==============================================

- stage: DeployToPyPI
  dependsOn: TestWheel
  
  jobs:
  - job: Placeholder
    pool: server
    
    steps:
    - task: Delay@1
      displayName: "Placeholder Pause"
      inputs:
        delayForMinutes: "0"

# ==============================================

- stage: TestFromPyPI
  dependsOn: DeployToPyPI

  jobs:
  - job: Placeholder
    pool: server
    
    steps:
    - task: Delay@1
      displayName: "Placeholder Pause"
      inputs:
        delayForMinutes: "0"